name: Verify markdown links in Kyma project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  verify-links:
    strategy:
      matrix:
        repository:
          # - kyma
          - btp-manager
          - istio
          # - serverless-manager
          # - telemetry-manager
          # - eventing-manager
          # - api-gateway
          # - nats-manager
          # - application-connector-manager
          # - keda-manager  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install md-check-link
        run: npm install -g md-check-link
      - name: Checkout ${{matrix.repository}}
        uses: actions/checkout@v2
        with:
          repository: kyma-project/${{matrix.repository}}
          path: ${{matrix.repository}}
      - name: Verify links
        run: |
          md-check-link -q -n 8 -c .mlc.config.json ./${{matrix.repository}}
        
