name: Verify markdown links in Kyma project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  install-md-check-link:
    runs-on: ubuntu-latest
    steps:
      - name: Install md-check-link
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install md-check-link
        run: npm install -g md-check-link
  verify-links:
    strategy:
      matrix:
        repository:
          - kyma
          - btp-manager
          - istio
    runs-on: ubuntu-latest
    needs: install-md-check-link
    steps:
      - name: Checkout Kyma
        uses: actions/checkout@v2
        with:
          repository: kyma-project/${{matrix.repository}}
          path: ${{matrix.repository}}
      - name: Verify links
        run: |
          md-check-link -q -n 8 -c .mlc.config.json ./${{matrix.repository}}
        
